### ISSUE TITLE
[bug] CLI should obey value set in `LOG_LEVEL` environment variable

### ISSUE THREAD

**Issue by gofford** [godatadriven/dbt-bouncer#276]
### Current Behavior

Currently, if the `LOG_LEVEL` environment variable is set to any string value then `dbt-bouncer` will _always_ run at the `logging.DEBUG` level:

https://github.com/godatadriven/dbt-bouncer/blob/b53a05be47e503206a713dc3864cfb15b0bbb64d/src/dbt_bouncer/logger.py#L51-L54

### Expected Behavior

`dbt-bouncer` should obey the value of the `LOG_LEVEL` variable. If `LOG_LEVEL=INFO` is set in my environment then I would expect the `dbt-bouncer` logger to emit only `INFO` statements -- currently it will emit at the `DEBUG` level.

### Steps To Reproduce

- Set `LOG_LEVEL=INFO` in the environment. 
- run `dbt-bouncer`. Observe the `DEBUG` logging.
- `unset LOG_LEVEL`
- run `dbt-bouncer` Observe `INFO` logging.

### Environment

```markdown
- OS: MacOS Sequoia 15.1 (beta)
- Python: 3.10.15
- dbt-bouncer: 1.3.3
```

**Comment by pgoslatara** [comment]
Thanks @gofford! Fixed in #281 and released in [1.3.4](https://github.com/godatadriven/dbt-bouncer/releases/tag/v1.3.4).
