### ISSUE TITLE
[question] exclude or omit specific files

### ISSUE THREAD

**Issue by gofford** [godatadriven/dbt-bouncer#277]
Is there a recommended way to exclude specific files from a check? The `include` and `exclude` parameters are regex-based and better suited for excluding folders on a path. The regex can get quite complicated if I, for example, wanted to include a set of paths but exclude a subset of files within that path.

Context: In general we want our developers to follow the `check_source_used_by_only_one_model` design. However, we also have a number of sources containing webhook data from multiple pub/sub topics which are unpacked in dbt base models before passing on to staging tables. In practice this is a 1:many source fan-out which fails the `check_source_used_by_only_one_model` check. 

It would be nice to be able to exclude individual files by name rather than regex.

**Comment by pgoslatara** [comment]
@gofford The design choice to use regex for `exclude` and `include` was to cater for nearly all possible configuration options. Indeed the resulting regex may not be pretty, but nearly all possible options are possible.

I'm struggling to follow your use case in detail. Are you following the [dbt recommendation](https://docs.getdbt.com/best-practices/how-we-structure/2-staging#staging-other-considerations) to store your base models in `base` directories and have the model names start with `base_*`? Does this lead to a usable regex pattern?

**Comment by pgoslatara** [comment]
Just did some testing, if I understand your setup then the following will suffice:
```yaml
manifest_checks:
  - name: check_source_used_by_only_one_model
    exclude: .*base.*
```

I feel like I'm missing something.

**Comment by gofford** [comment]
Thanks for replying! Apologies for not explaining this more thoroughly. 

My use-case in more detail: 

- We have a single bigquery table that contains webhooks from various Shopify topics, called `webhook_messages`. 
- Topics from this table are expanded into multiple staging tables for each topic, violating the `check_source_used_by_only_one_model` check. 
- I was looking for a way to have the `check_source_used_by_only_one_model` apply globally, _except_ for this specific table. 

Pushing the complexity down to the base layer and excluding it would resolve the issue. I hadn't looked at applying a regex for the table name itself. I'll look at that today.

**Comment by pgoslatara** [comment]
I still feel like I am mis-understanding your setup so please correct me again if required.

You mention "a single bigquery table" and "multiple staging tables", so my assumption is that you have one source defined and multiple direct downstream staging models. In this case, can you split the source into a dedicated `_sources.yml` file? I know that is against dbt recommendations but if you can then something like this is rather simple to implement and understand:
```yml
manifest_checks:
  - name: check_source_used_by_only_one_model
    exclude: models/path/to/_sources.yml
```
